title: <p align="center"> Nguyen Hoang Minh </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/minh-nguyen-9a1729234/">LinkedIn</a> |
  <a href="https://github.com/RyseUp">GitHub</a>
  </p>
  <p align="center"><strong>.NET Developer Internship.</strong></p>
  <p align="justify">
  I am junior student of Information Technology, majoring in Software Engineer at Saigon University.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
